### ISSUE TITLE
error after executing the code

### ISSUE THREAD

**Issue by bit-scientist** [EikeSan/video-fall-detection#2]
Hi @EikeSan it's a pretty light program with opencv, thank you for this. But when I run the program,the error occurs as the video finishes. 
```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp, line 11111
Traceback (most recent call last):
  File "new.py", line 15, in <module>
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11111: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor
```

I think that very error is preventing me from saving it with `VideoWriter` object? Can you look at your code and fix the error, because I couldn't yet. If possible include the saving part also. Thanks!

**Comment by EikeSan** [comment]
Hello @bit-scientist,
Sorry took so long to answer you, things are quite busy.
So, maybe it's a wrong file source path and couldn't load the image. I made a quick search about the problem and find this [link](http://answers.opencv.org/question/175328/opencv-error-assertion-failed-scn-3-scn-4-in-cvtcolor/).
I hope it can help you, and again sorry about the wait.
