### ISSUE TITLE
i think 

### ISSUE THREAD

**Issue by wangyongqiang2** [EikeSan/video-fall-detection#3]
hi,i think your idea is so easy .it can not be used really.

**Comment by EikeSan** [comment]
@wangyongqiang2 Tell me more

**Comment by lishuchao012** [comment]
if falling direction is same to camera direction, width is less than height, your result will be wrong

**Comment by EikeSan** [comment]
@lishuchao012 Indeed, There's a lot of points wich needs improvements, If I have an object into the frame it can be detected as wrog fall. Feel free to find a solution and contribute :smile: and thx for the feedback
